export enum ShopType {
     //PICKUPANDDROP = "PICKUP AND DROP",
     FRUITANDVEGETABLES = "FRUIT AND VEGETABLES",
     HEALTHANDWELLNESS  = "HEALTH AND WELLNESS",
     MEDICINES  = "MEDICINES",
     GROCERIES  = "GROCERIES"
}
